#!/bin/bash

###############################
#	VARIABLES

#Get current working directory
wdir=/usr/lib/marchobmenu

#Monitored directory
appdir=/usr/share/applications

#Root lock
rootlock=/tmp/rootlock

##############################


#kill appwatch daemon if running
ps -eo pid,user,args --sort pid | grep "inotifywait -q -m -r --format %e %w%f -e create -e delete $appdir" | sed -e '/grep/ d' | while read line
do
	if [ ! -z "$line" ]
	then
#		echo "daemon found $line"
		pid=`echo $line | cut -d ' ' -f1`
#		echo "killing $pid"
		kill $pid
	fi
done


#remove root lock
if [ -f $rootlock ]
then
	rm $rootlock
fi


###############################
#Now that we have a clean slate, we consider start|stop parameters

case "$1" in

#First start
  start|restart)


###############################
#	APP WATCH FUNCTION

function appwatch {

#inotify watch

inotifywait -q -m -r --format '%e %w%f' -e create -e delete $appdir | while read line
do

#Check if other entries are being processed	
	while [ -f $rootlock ]
	do
		echo "Entries being processed"
		sleep 2
	done
#/End of check and wait

		appfile=`echo $line | grep .desktop`
		if [ ! -z "$appfile" ]
		then
		touch $rootlock
		$wdir/./postchange $appfile
		rm $rootlock
		fi

done
}


###############################

#Run functions
appwatch &
echo "marchobmenu (re)started"
exit
	;;

#Second, stop
  stop)
  	echo "marchobmenu stopped"
  	exit
  	;;

#Third, usage instructions
  *)
	echo "Usage: marchobmenu-rootdaemon [start|stop|restart]" >&2
	exit 3
	;;
esac

exit
