#!/bin/bash

echo "============================> $0"

#Remove lock
if [ -f $usrlock ]
then
  echo "Removing user lock $usrlock"
	rm $usrlock
fi

#inotify watch

inotifywait -q -m -r --format '%f' -e create $trigdir | while read line; do
{
  # Check if other entries are being processed	
	echo "!!! CHANGE DETECTED IN $line !!!"
	sleep 1
	while [ -f $usrlock ] && [ -f $rootlock ]; do
  {
  	echo "Waiting for other entries being processed"
		sleep 2
  }
	done
  # /End of check and wait

  # Lock menu
  touch $usrlock

  #############################################
  #		UPDATE MENU
  #--------------------------------------------
  cat $trigdir/$line
  #Assign change to variable
  list=`cat $trigdir/$line`

  #Run updater
  echo "Updating $list"
  $appdir/./update $list
  echo "Done"
  #		/UPDATE MENU
  #############################################

  #Unlock menu
  rm $usrlock

  #remove trigger
  rm $trigdir/$line
}
done
