#! /bin/bash

set -u

################################################################################
#		VARIABLES
#-------------------------------------------------------------------------------
APP_PATH=$(readlink -f $0)
APP_DIR=$(dirname $APP_PATH)
APP_DAEMON=$(basename $APP_PATH)

PID=$$

# Needed if script was called with sudo
USER=$(who am i | sed 's/ .*//')
HOME=/home/$USER

WDIR="$HOME/.config/openbox/marchobmenu"
if [[ ! -d $WDIR ]]
then
  mkdir -p $WDIR
fi

LOGFILE="$WDIR/$APP_DAEMON.log"
PIDFILE="$WDIR/$APP_DAEMON.pid"

BUILD_CMD="$APP_DIR/mom.py"
CACHE_FILE="$WDIR/menu.cache"

PKG_NAME='marchobmenu'
TRIGGERS_DB="/var/lib/dpkg/triggers/File"

MONITORED=(
  # .directory files
  [0]="/usr/share/desktop-directories"
  [1]="/usr/local/share/desktop-directories"
  [2]="/home/*/.local/share/desktop-directories"
  # .desktop files
  [3]="/usr/share/applications"
  [4]="/usr/local/share/applications"
  [5]="/home/*/.local/share/applications"
  # LXDE Stuff
  [6]="/etc/xdg/menus/lxde-applications-merged"
  [7]="/home/*/.config/menus/lxde-applications-merged"
)
EXCLUDED=(
  [0]="/.local/share/applications/menu-xdg/"
)

#-------------------------------------------------------------------------------
#		/VARIABLES
################################################################################



################################################################################
#		FUNCTIONS
#-------------------------------------------------------------------------------
check_triggers()
{
  if grep $PKG_NAME $TRIGGERS_DB
  then
    cat << _ERROR
  Uh oh...
  It seems you have dpkg-triggers running for $PKG_NAME
  You must disable them before starting the daemon.
  Run:
  $ $APP_PATH disable-triggers
  Or:
  $ $APP_PATH --help
  if you want to know more about dpkg-triggers
_ERROR
    exit 1
  fi
}

compute_watches()
{
  # Get watched directories for the current user
  WATCHES=$(for d in "${MONITORED[@]}"
  do
    tmp=$(echo "$d" | sed "s/*/$USER/" )
    if [[ -d $tmp ]]; then echo "$tmp"; fi;
  done)
  # Get excludes patterns
  EXCLUDES=$(for pattern in "${EXCLUDED[@]}"
  do
    echo "--exclude $pattern "
  done)
}

watch()
{
  compute_watches
  inotifywait -qmr --format '%e %w%f' \
    -e create -e delete -e move -e modify \
    $EXCLUDES \
    $WATCHES | while read line
    do
      echo $line >> $LOGFILE
      update
    done 
}

signal_handler()
{
  stop
}
#################################################
# Public API
#------------------------------------------------
start()
{
  check_triggers
  stop
  update  
  nohup $0 run  >$LOGFILE 2>&1 &
  exec 3>&-
  exec 2>&-
  exec 1>&-
  exit 0
}

run()
{
  trap "signal_handler; exit" INT TERM EXIT
  echo $PID > $PIDFILE
  watch
  trap - INT TERM EXIT
}

stop()
{
  compute_watches
  pkill -u "$USER" \
    -f "inotifywait -qmr --format %e %w%f -e create -e delete -e move -e modify $EXCLUDES $WATCHED"
  pkill -u "$USER" -f "$APP_DAEMON"
  if [[ -f "$PIDFILE" ]] ; then rm "$PIDFILE" ; fi  
}

update()
{
  $BUILD_CMD > $CACHE_FILE
}

show()
{
  cat $CACHE_FILE
}

disable_triggers()
{
  if [[ -e $TRIGGERS_DB ]]
  then
    sudo sed -i -e "/$PKG_NAME$/d" $TRIGGERS_DB
  else
    echo "Your system doesn't support dpkg-triggers. Please use the daemon instead."
    exit 1
  fi
}

enable_triggers()
{
  if [[ -e $TRIGGERS_DB ]]
  then
    stop
    disable_triggers
    for d in "${MONITORED[@]}"
    do
      echo "$d $PKG_NAME" | sudo tee -a $TRIGGERS_DB
    done
  else
    echo "Your system doesn't support dpkg-triggers. Please use the daemon instead."
    exit 1
  fi
}

synopsis()
{
cat << _USAGE
$APP_DAEMON - monitors installed applications to generate a an Openbox PipeMenu

Synopsis
--------
$APP_DAEMON help             - Prints the help message and exits
$APP_DAEMON start            - Starts the menu daemon
$APP_DAEMON stop             - Stops the menu daemon
$APP_DAEMON update           - Regenerates the menu
$APP_DAEMON add-triggers     - Add dpkg-triggers (see mom-daemon help for more infos)
$APP_DAEMON remove-triggers  - Remove dpkg-triggers (see mom-daemon help for more infos)
_USAGE
}

usage ()
{
  synopsis
cat << _USAGE
About dpkg-triggers:
--------------------
  dpkg-triggers are a Debian/Apt specific way to trigger actions
  when a new package is installed/removed.
  They allow MarchOBMenu to update the menu without the overhead
  of running a daemon.

  However, they only work with packages installed by apt or dpkg.
  This is why they are not enabled by default.

  If you wish to activate this feature, first stop the daemon:
  $ $APP_PATH stop
  Then execute:
  $ $APP_PATH enable-triggers

  From now on, if you install a program in a non-standard way,
  like compiling from source, or a wine application,
  you'll need to explicitly update the menu by executing:
  $ $APP_PATH update

  You can deactivate this feature later it by executing:
  $ $APP_PATH disable-triggers
_USAGE

}
#-------------------------------------------------------------------------------
#		/FUNCTIONS
################################################################################




################################################################################
#		MAIN
#-------------------------------------------------------------------------------
case "$1" in
  start|restart)
    start
  ;;
  run)
    run
  ;;
  stop)
    stop
  ;;
  update)
    update
  ;;
  show)
    show
  ;;
  disable-triggers)
    disable_triggers
  ;;
  enable-triggers)
    enable_triggers
  ;;
  help)
    usage
  ;;
  *)
    synopsis
  ;;
esac
#-------------------------------------------------------------------------------
#		/MAIN
################################################################################

