#!/bin/bash

echo "============================> $0"

#############################################
#		ROOT MENU GENERATOR
#--------------------------------------------
#

#	GENERATE EACH ENTRY IF REQUIRED
# --------------- Accessories
item=
if [ -f "$wdir/submenus/Accessories" ]; then
{
  item=`sed '1!d' "$appdir/locale/$lang"`
	accessories="
<menu id=\"marchobmenu-accessories\" label=\"$item\">
`cat $wdir/submenus/Accessories`
</menu>"
}
else
{
  accessories=
}
fi

# ------------------- Games
item=
if [ -f "$wdir/submenus/Games" ]; then
{
  item=`sed '2!d' "$appdir/locale/$lang"`
	games="
<menu id=\"marchobmenu-games\" label=\"$item\">
`cat $wdir/submenus/Games`
</menu>"
}
else
{
  games=
}
fi

# ------------------- Graphics
item=
if [ -f "$wdir/submenus/Graphics" ]; then
{
	item=`sed '3!d' "$appdir/locale/$lang"`
	graphics="
<menu id=\"marchobmenu-graphics\" label=\"$item\">
`cat $wdir/submenus/Graphics`
</menu>"
}
else
{
  graphics=
}
fi

# -------------------- Internet
item=
if [ -f "$wdir/submenus/Internet" ]; then
{
	item=`sed '4!d' "$appdir/locale/$lang"`
	internet="
<menu id=\"marchobmenu-internet\" label=\"$item\">
`cat $wdir/submenus/Internet`
</menu>"
}
else
{
  internet=
}
fi

# --------------------- Office
item=
if [ -f "$wdir/submenus/Office" ]; then
{
	item=`sed '5!d' "$appdir/locale/$lang"`

	office="
<menu id=\"marchobmenu-office\" label=\"$item\">
`cat $wdir/submenus/Office`
</menu>"
}
else
{
  office=
}
fi

# ---------------------- Others
item=
if [ -f "$wdir/submenus/Others" ]; then
{
	item=`sed '6!d' "$appdir/locale/$lang"`

	others="
<menu id=\"marchobmenu-others\" label=\"$item\">
`cat $wdir/submenus/Others`
</menu>"
}
else
{
  others=
}
fi

# ---------------------- Programming
item=
if [ -f "$wdir/submenus/Programming" ]; then
{
	item=`sed '7!d' "$appdir/locale/$lang"`

	programming="
<menu id=\"marchobmenu-programming\" label=\"$item\">
`cat $wdir/submenus/Programming`
</menu>"
}
else
{
  programming=
}
fi

# --------------------- Sound & Video
item=
if [ -f "$wdir/submenus/Multimedia" ]; then
{
	item=`sed '8!d' "$appdir/locale/$lang"`

	multimedia="
<menu id=\"marchobmenu-multimedia\" label=\"$item\">
`cat $wdir/submenus/Multimedia`
</menu>"
}
else
{
  multimedia=
}
fi

# --------------------- Wine
item=
if [ -f "$wdir/submenus/Wine" ]; then
{
	item=`sed '14!d' "$appdir/locale/$lang"`

	multimedia="
<menu id=\"marchobmenu-wine\" label=\"$item\">
`cat $wdir/submenus/Wine`
</menu>"
}
else
{
  multimedia=
}
fi

# --------------------- System Tools
item=
if [ -f "$wdir/submenus/System" ]; then
{
	item=`sed '13!d' "$appdir/locale/$lang"`

	wine="
<menu id=\"marchobmenu-system\" label=\"$item\">
`cat $wdir/submenus/System`
</menu>"
}
else
{
  wine=
}
fi

# --------------------- Preferences
item=
if [ -f "$wdir/submenus/Preferences" ]; then
{
	item=`sed '12!d' "$appdir/locale/$lang"`

	preferences="
<menu id=\"marchobmenu-preferences\" label=\"$item\">
`cat $wdir/submenus/Preferences`
</menu>"
}
else
{
  preferences=
}
fi

echo "<openbox_pipe_menu>
  $accessories
  $games
  $graphics
  $internet
  $office
  $others
  $programming
  $multimedia
  $wine
  $preferences
  $system
  
</openbox_pipe_menu>" > "$wdir/applications.xml"

#
#		/ROOT MENU GENERATOR
#############################################
