#!/bin/bash

echo "============================> $0"

## debug
#export wdir="$HOME/.config/openbox/marchobmenu"
#export appdir=/usr/lib/marchobmenu
#export usrname=`whoami`
#export lang=fr

#############################################
#		CREATE ENTRY
#--------------------------------------------

if [ "$1" = "CREATE" ]; then
{
  echo "Creating entry $2"
  #############################################
  #		PARSER
  #--------------------------------------------
  #Run parser to parse .desktop file one by one
  while [ ! -z "$2" ]; do
  {
	  #sh $appdir/parser $2
	  $appdir/parser $2
    shift
  }
  done
  #		/PARSER
  #############################################

  #############################################
  #		SORTING
  #--------------------------------------------
  #Assign list of submenus to be sorted to variable
  sortqueue=`cat $wdir/sortqueue`
  #Run sorter to sort submenus
  #sh $appdir/sorter $sortqueue
  $appdir/sorter $sortqueue
  #		/SORTING
  #############################################
  
  $appdir/./rootgen $lang

}
fi

#		/CREATE ENTRY
#############################################

#############################################
#		DELETE ENTRY
#--------------------------------------------

if [ "$1" = "DELETE" ]; then
{
  echo "Deleting entry $2"

  function delete()
  {
	  var=`cat $wdir/submenus/$submenu | grep "$target"`
	  # echo "var is $var"
    # edit target for sed
	  target2=`echo $target | sed 's/\//\\\\\//g'`
	  # echo "target2 is $target2"

	  if [ -n "$var" ]; then
	  {
	  	echo "Entry found. Now removing"
		  sed -e /"$target2"/d $wdir/submenus/$submenu > /tmp/"$usrname""$submenu"
		  echo "/tmp/"$usrname""$submenu" created"
		  rm $wdir/submenus/$submenu
		  cp /tmp/"$usrname""$submenu" $wdir/submenus/$submenu
      # rm /tmp/"$usrname""$submenu"
		  echo "Remove done"
      # remove submenu if empty
		  content=`cat $wdir/submenus/$submenu`
		  if [ -z "$content" ]; then
		  {
		  	rm $wdir/submenus/$submenu
			  #run rootgenfor system langauge
			  # $appdir/./rootgen $lang
		  }
		  fi
	  }
	  fi

  }

  while [ ! -z "$2" ]; do
  {
    target=$2

    submenu=Accessories
    delete
    submenu=Games
    delete
    submenu=Graphics
    delete
    submenu=Internet
    delete
    submenu=Multimedia
    delete
    submenu=Office
    delete
    submenu=Others
    delete
    submenu=Programming
    delete
    submenu=System
    delete
    submenu=

    shift 
  }
  done
  
  $appdir/./rootgen $lang
  
}
fi
#		/DELETE ENTRY
#############################################

exit
