#!/bin/sh
### BEGIN INIT INFO
# Provides:          marchobmenu
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Starting marchobmenu daemon.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
[ "$DELAYLOGIN" ] || DELAYLOGIN=yes
. /lib/init/vars.sh


case "$1" in
  start|restart)
	  cd /usr/lib/marchobmenu
	  ./marchobmenu-rootdaemon start &> /dev/null
	  cd
	  exit
	;;
  stop)
	  cd /usr/lib/marchobmenu
	  ./marchobmenu-rootdaemon stop &> /dev/null
	  cd
	  exit
	;;
  *)
	  echo "Usage: marchobmenu [start|stop|restart]" >&2
	  exit 3
	;;
esac

exit
